services:
  apicielo:
    build: .
    container_name: apicielo-app
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/apicielo
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 326598

  mysql:
    image: mysql:8.0
    container_name: apicielo-mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 326598
      MYSQL_DATABASE: apicielo
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
