# Configuração de acesso ao banco de dados (exemplo com MySQL)
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/apicielo
    username: root
    password: 326598
    driver-class-name: com.mysql.cj.jdbc.Driver  # Especifica explicitamente o driver do MySQL
  jpa:
    hibernate:
     ddl-auto: none  # O Flyway vai gerenciar as migrações
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    driver-class-name: com.mysql.cj.jdbc.Driver  # Adiciona essa linha para garantir que o driver correto seja utilizado
# Token de acesso ao ambiente de Sandbox da Cielo
cielo:
  merchant:
    id: 6a83e1f0-5ce6-4108-8cfa-b621ce3efcf6
    key: CXMIYMXHTXLSXARRYLLUKBMSYUARVXCLVPXRKMNF

# Configurações de logs
logging:
  level:
    org.springframework.web: DEBUG
    com.apicielo.projeto: DEBUG

